#!/bin/bash
cd homework/ 
mkdir test_1 test_2 test_3 
cd test_1/
touch work_1.txt work_2.txt work_3.txt work_4.json work_5.json 
mkdir test_4 test_5 test_6
ls -la 
mv ~/Desktop/group_27/Homework/test_1/work_{1,2}.txt ~/Desktop/group_27/Homework/test_2
